version: '3.9'
services:
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - ./:/app
    
    # depends_on:
    #   - mongodb
    #   - mongo-express
    # networks:
    #   - skills-network
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27018:27017
    command: mongod --auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE_NAME}
    volumes:
      - $MONGODB_DATA_DIR:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - apollo-network
  mongo-express:
    image: mongo-express:0.54.0
    container_name: mongo-express
    restart: always
    environment: 
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME="${MONGO_ROOT_USER}"
      - ME_CONFIG_MONGODB_ADMINPASSWORD="${MONGO_ROOT_PASSWORD}"
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
      - ME_CONFIG_MONGODB_PORT=27017    
    depends_on:
            - mongodb
    ports:
          - "8081:8081"
    networks:
      - apollo-network
networks:
  apollo-network:
    
    external: true    
    driver: bridge  
  
      


